server:
  port: 8084

spring:
    application:
      name: notification

    datasource:
        username: 'zigma96'
        url: jdbc:postgresql://localhost:5432/notifications
        password: 'password'
    jpa:
        hibernate:
          ddl-auto: create-drop
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
        show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

