#insted of localhost name of the container is used
spring:
  application:
    name:  eureka-server
  zipkin:
    base-url: http://zipkin:9411
server:
  port: 8761
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
